### PR TITLE
Fix thread leak on close when pubAckMap is null

### PR DESCRIPTION
**Pull request by tjmcarthur**
#141

### CODE REVIEW

**Comment by sasbury** [comment]
ignore checks, something is up with travis

I will take a look this week, sorry it is slow we are trying to get a big release out tomorrow for something else so I can't swap gears fast enough to get to this today. But I will try.

**Comment by sasbury** [comment]
BTW my plan is to do a really minor release with just this and maybe 1 other fix.

**Comment by sasbury** [comment]
Merging into 2.2.3 branch, as I said, I am swamped, but will try to get this out later in the week once look at the other open issues

**Comment by tjmcarthur** [comment]
Thanks!

**Pull request merged**
